import baseConfig from "__REPO_ROOT__/packages/excali-local/wxt.config.ts";

// Generated by the excali-local-test skill (scripts/dev-server.mjs) — do not edit.
//
// Dev-only wxt config: run the wxt dev server WITHOUT launching a browser.
// webExt.disabled switches WXT to the "manual runner" — the dev server and
// the .output/<browser>-mv3-dev build are produced, but no Chrome is spawned.
// The test browser is the chrome-devtools MCP browser (CDP-managed), and the
// built extension is loaded into it via install_extension.

export default {
  ...baseConfig,
  webExt: { disabled: true },
};
